### ISSUE TITLE
Showing All Messages ERROR Can not get issues 504: Gateway Timeout

### ISSUE THREAD

**Issue by huos3203** [tcatche/hexo-generator-issues#1]
Showing All Messages ERROR Can not get issues 504: Gateway Timeout

_config.yml 
```yml
issues:
  auth:
#    # Auth type,More in https://github.com/mikedeboer/node-github#authentication
    type: oauth  #basic
    # Auth from token https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
    token: 9473b2881deb7d2faa68faccff7f*******
    # Auth from client keys
    id:
    secret:
    # Auth from credentials
    username: huos3203
    password: 9473b2881deb7d2faa68faccff7f*******
  repository: # The issue repository.
    owner: huos3203 # `userName`
    repo: huos3203.github.io # `repositoryName`
#sourceLink:
#    position: top #or `bottom` or `false`
#    template: '' #  The default template is
```
can you help ? thanks
